#3、在配置文件 application.yml 添加 Config Server 相关配置
server:
  port: 8762 # 当前 Config Server 服务端口
spring:
  application:
    name: nativeconfigserver # 当前服务注册在 Eureka Server 上的名称
  profiles:
    active: native # 配置文件获取方式
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared # 本地配置文件的存放路径
#          ++
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/ # 注册中心的访问地址
  instance:
    prefer-ip-address: true # 是否将当前服务的 IP 注册到 Eureka Server
