#3、在 application.yml 添加 Zipkin 相关配置
server:
  port: 8090 # 当前 Zipkin Client 服务端口
spring:
  application:
    name: zipkinclient # 当前服务注册在 Eureka Server 上的名称
  sleuth:
    web:
      client:
        enabled: true # 设置是否开启 Sleuth
    sampler:
      probability: 1.0 # 设置采样比例，默认是 0.1
  zipkin:
    base-url: http://localhost:9090/ # Zipkin Server 地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/ # 注册中心的访问地址
