#3、在配置文件 application.yml 添加 Hystrix 相关配置
server:
  port: 8060 # 当前 Hystrix 服务端口
spring:
  application:
    name: hystrix # 当前服务注册在 Eureka Server 上的名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/ # 注册中心的访问地址
  instance:
    prefer-ip-address: true # 是否将当前服务的 IP 注册到 Eureka Server
feign:
  hystrix:
    enabled: true # 是否开启熔断器
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' # 用来暴露 endpoints 的相关信息
